---
- name: ðŸ”¥ Install firewall package
  package:
    name:
      - ufw
    state: present
  tags:
    - config.firewall

- name: ðŸ”¥ Deny all ingress connections
  ufw:
    policy: deny
    direction: incoming
  tags:
    - config.firewall

- name: ðŸ”¥ allow ingress ssh
  ufw:
    rule: allow
    port: ssh
    proto: tcp
    direction: in
  tags:
    - config.firewall

- name: ðŸ”¥ allow rpc ingress port
  ufw:
    rule: allow
    proto: tcp
    direction: in
    port: '{{ solana_rpc_port }}'
  tags:
    - config.firewall

- name: ðŸ”¥ allow ingress solana udp ports
  ufw:
    rule: allow
    proto: udp
    direction: in
    port: '{{ open_solana_ports_start }}:{{ open_solana_ports_end }}'
  tags:
    - config.firewall

- name: ðŸ”¥ allow ingress solana tcp ports
  ufw:
    rule: allow
    proto: tcp
    direction: in
    port: '{{ open_solana_ports_start }}:{{ open_solana_ports_end }}'
  tags:
    - config.firewall

- name: ðŸ”¥ Enable ufw
  ufw:
    state: enabled
  tags:
    - config.firewall
