---

- name: ğŸ“¦ Install additional packages
  import_tasks: packages.yaml
  tags:
    - config.packages

- name: ğŸ¤¹ Create swap
  import_tasks: swap.yaml
  tags:
    - config.swap
  when: swap_file_size_gb | int  > 0

- name: ğŸ’¾ Create ramdisk
  import_tasks: ramdisk.yaml
  tags:
    - config.ramdisk
  when: use_ramdisk_for_account

- name: ğŸ Config cpu governor performance mode
  import_tasks: governor.yaml
  tags:
    - config.cpu

- name: ğŸ”¥ Config firewall
  import_tasks: firewall.yaml
  tags:
    - config.firewall
  when:
    use_firewall | bool

- name: ğŸš« Config file2ban
  import_tasks: fail2ban.yaml
  tags:
    - config.fail2ban

- name: ğŸ¸ Create solana user
  import_tasks: solana_user.yaml
  tags:
    - config.solana_user
    - validator.service.solana

- name: ğŸ”§ Config sysctl
  import_tasks: sysctl.yaml

- name: âŒš chronly
  import_tasks: chronly.yaml

