---

- name: ðŸ“¦ packages | ensure apt list dir exists
  file:
    path: /var/lib/apt/lists/
    state: directory
    mode: 0755

- name: ðŸ“¦ Update apt cache
  become: yes
  apt:
    update_cache: yes

- name: ðŸ“¦ Install additional packages
  become: yes
  apt:
    pkg:
      - gpg
      - gpg-agent
      - ufw
      - rsyslog
      - update-motd
  tags:
    - config.packages
