---
- name: ğŸ¸ Ensure group solana exists
  ansible.builtin.group:
    name: "{{ solana_user }}"
    state: present

- name: ğŸ¸ Create user solana
  user:
    name: "{{ solana_user }}"
    state: present
    create_home: yes
    shell: /bin/bash
    skeleton: /etc/skel
    force: yes
    groups:
      - "{{ solana_user }}"
      - syslog
  tags:
    - config.solana_user
    - validator.service.solana

- name: ğŸ¸ Create secrets dir
  become: yes
  file:
    path: "{{ secrets_path }}"
    state: directory
    mode: '0700'
    owner: "{{ solana_user }}"
  tags:
    - config.solana_user
    - validator.service.solana

#- name: ğŸ¸ Create ledger directory
#  become: yes
#  file:
#    path: "{{ ledger_path }}"
#    owner: "{{ solana_user }}"
#    group: "{{ solana_user }}"
#    state: directory
#    mode: '0755'
#  tags:
#    - config.solana_user
#    - validator.service.solana
#
#- name: ğŸ¸ set account path for disk
#  set_fact:
#    accounts_path: "{{ mount_base_path }}/accounts"
#  when: not use_ramdisk_for_account
#  tags:
#    - config.solana_user
#    - validator.service.solana
#
#- name: ğŸ¸ set account path for ramdisk
#  set_fact:
#    accounts_path: "{{ ramdisk_path }}/accounts"
#  when: use_ramdisk_for_account
#  tags:
#    - config.solana_user
#    - validator.service.solana

#- name: ğŸ¸ Create accounts directory on disk
#  become: yes
#  file:
#    path: "{{ accounts_path }}"
#    owner: "{{ solana_user }}"
#    group: "{{ solana_user }}"
#    state: directory
#    mode: '0755'
#  tags:
#    - config.solana_user
#    - validator.service.solana
#
#- name: ğŸ¸ Create snapshots directory
#  become: yes
#  file:
#    path: "{{ snapshots_path }}"
#    owner: "{{ solana_user }}"
#    group: "{{ solana_user }}"
#    state: directory
#    mode: '0755'
#  tags:
#    - config.solana_user
#    - validator.service.solana
#
#- name: ğŸ¸ Create logs directory
#  become: yes
#  file:
#    path: "{{ validator_log_path }}"
#    owner: "{{ solana_user }}"
#    group: "{{ solana_user }}"
#    state: directory
#    mode: '0755'
#  tags:
#    - config.solana_user
#    - validator.service.solana
